version: "2"
services:
    node_server:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:3000"
            - "9229:9229"
        working_dir: /home/node/app
        
        volumes:
            - ./node:/home/node/app
        networks:
            - front
        tty: true
        stdin_open: true
        command: "bash"
networks:
    front: